package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"regexp"
	"strings"
	"syscall"
	"time"

	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/prometheus"
	"go.opentelemetry.io/otel/metric"
	sdkmetric "go.opentelemetry.io/otel/sdk/metric"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"

	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const (
	labelModel       = "model"
	labelEndpoint    = "endpoint"
	defaultUpstream  = "http://localhost:11434"
	defaultPort      = "8080"
	bytesPerMB       = 1024 * 1024
	serviceName      = "ollama-metrics"
)

var doneReasonRe = regexp.MustCompile(`"done_reason":(\d+)`)

type generateResponse struct {
	Model              string      `json:"model"`
	Done               *bool       `json:"done,omitempty"`
	Response           string      `json:"response,omitempty"`
	PromptEvalCount    *int        `json:"prompt_eval_count,omitempty"`
	EvalCount          *int        `json:"eval_count,omitempty"`
	TotalDuration      *int64      `json:"total_duration,omitempty"`
	EvalDuration       *int64      `json:"eval_duration,omitempty"`
	PromptEvalDuration *int64      `json:"prompt_eval_duration,omitempty"`
	DoneReason         interface{} `json:"done_reason,omitempty"`
}

type psResponse struct {
	Models []struct {
		Name      string `json:"name"`
		ID        string `json:"id"`
		Size      int64  `json:"size"`
		Processor string `json:"processor"`
		Until     string `json:"until"`
	} `json:"models"`
}

type modelsResponse struct {
	Models []struct {
		Name    string `json:"name"`
		Model   string `json:"model"`
		Size    int64  `json:"size"`
		Digest  string `json:"digest"`
		Details struct {
			ParentModel       string   `json:"parent_model"`
			Format            string   `json:"format"`
			Family            string   `json:"family"`
			Families          []string `json:"families"`
			ParameterSize     string   `json:"parameter_size"`
			QuantizationLevel string   `json:"quantization_level"`
		} `json:"details"`
		ExpiresAt string `json:"expires_at"`
		SizeVRAM  int64  `json:"size_vram"`
	} `json:"models"`
}

type metricsInstruments struct {
	promptTokens    metric.Int64Counter
	generatedTokens metric.Int64Counter
	requestDuration metric.Float64Histogram
	timePerToken    metric.Float64Histogram
	tokensPerSecond metric.Float64Histogram
	loadedModels    metric.Int64Gauge
	modelLoaded     metric.Int64Gauge
	modelRAMUsage   metric.Float64Gauge
}

func newMetricsInstruments(meter metric.Meter) (*metricsInstruments, error) {
	promptTokens, err := meter.Int64Counter(
		"ollama.prompt.tokens",
		metric.WithDescription("Total number of prompt tokens sent to the model"),
		metric.WithUnit("{token}"),
	)
	if err != nil {
		return nil, fmt.Errorf("create prompt_tokens: %w", err)
	}

	generatedTokens, err := meter.Int64Counter(
		"ollama.generated.tokens",
		metric.WithDescription("Total number of tokens generated by the model"),
		metric.WithUnit("{token}"),
	)
	if err != nil {
		return nil, fmt.Errorf("create generated_tokens: %w", err)
	}

	requestDuration, err := meter.Float64Histogram(
		"ollama.request.duration",
		metric.WithDescription("Duration of Ollama requests"),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0.1, 0.5, 1, 2, 5, 10, 30, 60),
	)
	if err != nil {
		return nil, fmt.Errorf("create request_duration: %w", err)
	}

	timePerToken, err := meter.Float64Histogram(
		"ollama.token.generation.time",
		metric.WithDescription("Time per generated token"),
		metric.WithUnit("s"),
		metric.WithExplicitBucketBoundaries(0.01, 0.05, 0.1, 0.2, 0.5, 1, 2),
	)
	if err != nil {
		return nil, fmt.Errorf("create time_per_token: %w", err)
	}

	tokensPerSecond, err := meter.Float64Histogram(
		"ollama.tokens.per_second",
		metric.WithDescription("Tokens per second generated by the model per request"),
		metric.WithExplicitBucketBoundaries(1, 5, 10, 20, 50, 100, 200, 500),
	)
	if err != nil {
		return nil, fmt.Errorf("create tokens_per_second: %w", err)
	}

	loadedModels, err := meter.Int64Gauge(
		"ollama.loaded.models",
		metric.WithDescription("Number of models currently loaded in memory in Ollama"),
	)
	if err != nil {
		return nil, fmt.Errorf("create loaded_models: %w", err)
	}

	modelLoaded, err := meter.Int64Gauge(
		"ollama.model.loaded",
		metric.WithDescription("Indicator (1/0) if a model is loaded in memory"),
	)
	if err != nil {
		return nil, fmt.Errorf("create model_loaded: %w", err)
	}

	modelRAMUsage, err := meter.Float64Gauge(
		"ollama.model.ram.usage",
		metric.WithDescription("RAM usage in megabytes for each loaded model"),
	)
	if err != nil {
		return nil, fmt.Errorf("create model_ram_usage: %w", err)
	}

	return &metricsInstruments{
		promptTokens:    promptTokens,
		generatedTokens: generatedTokens,
		requestDuration: requestDuration,
		timePerToken:    timePerToken,
		tokensPerSecond: tokensPerSecond,
		loadedModels:    loadedModels,
		modelLoaded:     modelLoaded,
		modelRAMUsage:   modelRAMUsage,
	}, nil
}

var upstreamClient = &http.Client{
	Timeout: 0,
}

func fixDoneReason(data []byte) []byte {
	return doneReasonRe.ReplaceAll(data, []byte(`"done_reason":"$1"`))
}

func ensureModelTag(modelName string) string {
	if modelName == "" {
		return "unknown"
	}
	if !strings.Contains(modelName, ":") {
		return modelName + ":latest"
	}
	return modelName
}

func refreshModelMetrics(ctx context.Context, addr string, m *metricsInstruments) {
	resp, err := upstreamClient.Get(addr + "/api/ps")
	if err != nil {
		slog.Error("Refresh model metrics failed", "error", err)
		return
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		slog.Error("Read /api/ps response failed", "error", err)
		return
	}

	var ps psResponse
	if err := json.Unmarshal(data, &ps); err != nil {
		slog.Error("Parse /api/ps response failed", "error", err)
		return
	}

	m.loadedModels.Record(ctx, int64(len(ps.Models)))

	for _, model := range ps.Models {
		name := ensureModelTag(model.Name)
		m.modelLoaded.Record(ctx, 1, metric.WithAttributes(attribute.String(labelModel, name)))
		ramMB := float64(model.Size) / bytesPerMB
		m.modelRAMUsage.Record(ctx, ramMB, metric.WithAttributes(attribute.String(labelModel, name)))
	}
}

func main() {
	slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	})))

	upstreamAddr := os.Getenv("OLLAMA_HOST")
	if upstreamAddr == "" {
		upstreamAddr = defaultUpstream
	}
	u, err := url.Parse(upstreamAddr)
	if err != nil {
		slog.Error("Invalid OLLAMA_HOST", "value", upstreamAddr, "error", err)
		os.Exit(1)
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		slog.Error("Invalid OLLAMA_HOST scheme", "scheme", u.Scheme)
		os.Exit(1)
	}
	if u.Host == "" {
		slog.Error("Invalid OLLAMA_HOST: no host specified", "value", upstreamAddr)
		os.Exit(1)
	}
	if u.User != nil {
		slog.Error("Invalid OLLAMA_HOST: embedded credentials not supported")
		os.Exit(1)
	}
	if u.Path != "" && u.Path != "/" {
		slog.Warn("Ignoring path in OLLAMA_HOST", "path", u.Path)
	}
	upstreamAddr = u.Scheme + "://" + u.Host

	port := os.Getenv("PORT")
	if port == "" {
		port = defaultPort
	}

	res, err := resource.New(context.Background(),
		resource.WithAttributes(
			semconv.ServiceName(serviceName),
		),
	)
	if err != nil {
		slog.Error("Create OTel resource failed", "error", err)
		os.Exit(1)
	}

	exporter, err := prometheus.New()
	if err != nil {
		slog.Error("Create Prometheus exporter failed", "error", err)
		os.Exit(1)
	}

	provider := sdkmetric.NewMeterProvider(
		sdkmetric.WithResource(res),
		sdkmetric.WithReader(exporter),
	)
	defer func() {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		if err := provider.Shutdown(ctx); err != nil {
			slog.Error("Meter provider shutdown failed", "error", err)
		}
	}()

	meter := provider.Meter(serviceName)

	metrics, err := newMetricsInstruments(meter)
	if err != nil {
		slog.Error("Create metrics instruments failed", "error", err)
		os.Exit(1)
	}

	slog.Info("Starting Ollama proxy sidecar", "upstream", upstreamAddr, "port", port)

	refreshModelMetrics(context.Background(), upstreamAddr, metrics)

	mux := http.NewServeMux()

	mux.HandleFunc("/metrics", func(w http.ResponseWriter, r *http.Request) {
		refreshModelMetrics(r.Context(), upstreamAddr, metrics)
		promhttp.Handler().ServeHTTP(w, r)
	})

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		if r.URL.Path == "/metrics" {
			promhttp.Handler().ServeHTTP(w, r)
			return
		}

		var bodyBytes []byte
		if r.Body != nil {
			var err error
			bodyBytes, err = io.ReadAll(r.Body)
			r.Body.Close()
			if err != nil {
				http.Error(w, "Failed to read request body", http.StatusInternalServerError)
				slog.Error("Read request body failed", "error", err)
				return
			}
		}

		targetURL := upstreamAddr + r.URL.Path
		if r.URL.RawQuery != "" {
			targetURL += "?" + r.URL.RawQuery
		}

		reqUp, err := http.NewRequest(r.Method, targetURL, bytes.NewReader(bodyBytes))
		if err != nil {
			http.Error(w, "Bad request", http.StatusInternalServerError)
			slog.Error("Create upstream request failed", "error", err)
			return
		}
		for name, vals := range r.Header {
			if name == "Host" {
				continue
			}
			for _, v := range vals {
				reqUp.Header.Add(name, v)
			}
		}
		if reqUp.Header.Get("Content-Type") == "" && len(bodyBytes) > 0 {
			reqUp.Header.Set("Content-Type", "application/json")
		}

		respUp, err := upstreamClient.Do(reqUp)
		if err != nil {
			http.Error(w, "Upstream error", http.StatusBadGateway)
			slog.Error("Forward request to upstream failed", "error", err)
			return
		}
		defer respUp.Body.Close()

		for name, vals := range respUp.Header {
			switch strings.ToLower(name) {
			case "transfer-encoding", "content-length", "connection",
				"keep-alive", "upgrade", "trailer", "proxy-connection",
				"proxy-authenticate", "proxy-authorization", "te":
				continue
			}
			for _, v := range vals {
				w.Header().Add(name, v)
			}
		}
		w.WriteHeader(respUp.StatusCode)

		var modelName string
		var promptCount, generatedCount int
		var evalDurationNs int64

		if r.URL.Path == "/api/generate" || r.URL.Path == "/api/chat" {
			var buf bytes.Buffer
			streamWriter := io.MultiWriter(w, &buf)
			flusher, _ := w.(http.Flusher)
			chunk := make([]byte, 1024)
			for {
				n, readErr := respUp.Body.Read(chunk)
				if n > 0 {
					if _, writeErr := streamWriter.Write(chunk[:n]); writeErr != nil {
						slog.Warn("Client write error during streaming", "error", writeErr)
						break
					}
					if flusher != nil {
						flusher.Flush()
					}
				}
				if readErr != nil {
					if readErr != io.EOF {
						slog.Error("Read upstream streaming response failed", "error", readErr)
					}
					break
				}
			}

			bufData := fixDoneReason(buf.Bytes())

			var modelsResp modelsResponse
			if err := json.Unmarshal(bufData, &modelsResp); err == nil && len(modelsResp.Models) > 0 {
				for _, model := range modelsResp.Models {
					modelName = ensureModelTag(model.Model)
					metrics.modelRAMUsage.Record(r.Context(),
						float64(model.SizeVRAM)/bytesPerMB,
						metric.WithAttributes(attribute.String(labelModel, modelName)),
					)
				}
				slog.Info("Received models list response", "count", len(modelsResp.Models))
			} else {
				for _, line := range bytes.Split(bufData, []byte{'\n'}) {
					if len(line) == 0 {
						continue
					}
					var res generateResponse
					if err := json.Unmarshal(line, &res); err != nil {
						slog.Warn("Failed to parse generate response line", "error", err)
						continue
					}
					if res.Model != "" {
						modelName = ensureModelTag(res.Model)
					}
					if res.Done != nil && *res.Done {
						if res.PromptEvalCount != nil {
							promptCount = *res.PromptEvalCount
						}
						if res.EvalCount != nil {
							generatedCount = *res.EvalCount
						}
						if res.EvalDuration != nil {
							evalDurationNs = *res.EvalDuration
						}
					}
				}
			}
		} else if r.URL.Path == "/api/ps" {
			data, err := io.ReadAll(respUp.Body)
			if err != nil {
				slog.Error("Read /api/ps response body failed", "error", err)
			} else {
				if _, err := w.Write(data); err != nil {
					slog.Error("Write /api/ps response to client failed", "error", err)
					return
				}
				refreshModelMetrics(r.Context(), upstreamAddr, metrics)
			}
			return
		} else {
			if _, err := io.Copy(w, respUp.Body); err != nil {
				slog.Error("Copy upstream response body failed", "error", err)
			}
			if len(bodyBytes) > 0 {
				var reqJson map[string]interface{}
				if err := json.Unmarshal(bodyBytes, &reqJson); err == nil {
					if m, ok := reqJson[labelModel].(string); ok {
						modelName = ensureModelTag(m)
					}
				}
			}
		}

		durationSec := time.Since(start).Seconds()

		if modelName != "" && respUp.StatusCode >= 200 && respUp.StatusCode < 300 {
			attrs := metric.WithAttributes(attribute.String(labelModel, modelName))

			if promptCount > 0 {
				metrics.promptTokens.Add(r.Context(), int64(promptCount), attrs)
			}
			if generatedCount > 0 {
				metrics.generatedTokens.Add(r.Context(), int64(generatedCount), attrs)
			}

			endpoint := strings.TrimPrefix(r.URL.Path, "/api/")
			if endpoint == "" {
				endpoint = r.URL.Path
			}
			metrics.requestDuration.Record(r.Context(), durationSec,
				metric.WithAttributes(
					attribute.String(labelModel, modelName),
					attribute.String(labelEndpoint, endpoint),
				),
			)

			if generatedCount > 0 && evalDurationNs > 0 {
				evalDurationSec := float64(evalDurationNs) / 1e9
				secondsPerToken := evalDurationSec / float64(generatedCount)
				metrics.timePerToken.Record(r.Context(), secondsPerToken, attrs)
				tokensPerSec := float64(generatedCount) / evalDurationSec
				metrics.tokensPerSecond.Record(r.Context(), tokensPerSec, attrs)
			}
		}

		if modelName != "" && (promptCount > 0 || generatedCount > 0) {
			slog.Info("Request completed",
				"method", r.Method,
				"path", r.URL.Path,
				"model", modelName,
				"prompt_tokens", promptCount,
				"generated_tokens", generatedCount,
				"duration_s", durationSec,
			)
		} else {
			slog.Info("Request completed",
				"method", r.Method,
				"path", r.URL.Path,
				"status", respUp.StatusCode,
				"duration_s", durationSec,
			)
		}
	})

	wrappedHandler := otelhttp.NewHandler(mux, "ollama-proxy",
		otelhttp.WithSpanNameFormatter(func(_ string, r *http.Request) string {
			return r.Method + " " + r.URL.Path
		}),
	)

	srv := &http.Server{
		Addr:              ":" + port,
		Handler:           wrappedHandler,
		ReadHeaderTimeout: 10 * time.Second,
		ReadTimeout:       30 * time.Second,
		WriteTimeout:      0,
		IdleTimeout:       120 * time.Second,
	}

	go func() {
		slog.Info("HTTP server listening", "addr", srv.Addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			slog.Error("HTTP server error", "error", err)
			os.Exit(1)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	slog.Info("Shutting down server...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		slog.Error("Server forced shutdown", "error", err)
		os.Exit(1)
	}
	slog.Info("Server exited")
}
